version: '3.7'
services:
    db-benfrio:
        container_name: db-benfrio
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pedidos
            MYSQL_USER: pedidos
            MYSQL_PASSWORD: pedidos
        networks:
            - db-benfrio
    php-benfrio:
        container_name: php-fpm-benfrio
        build: ./php-fpm
        ports:
            - "9000:9001"
        volumes:
            - ./projeto:/var/www/projeto:cached
        depends_on: 
            - db-benfrio
        networks:
            - db-benfrio
            - php-benfrio
    nginx-benfrio:
        container_name: nginx-benfrio
        build: ./nginx
        ports:
            - "80:80"
        depends_on: 
            - php-benfrio
        networks:
            - php-benfrio
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./projeto:/var/www/projeto:cached
networks:
    db-benfrio:
    php-benfrio: